name: "Build Server"

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request: # will remove after testing

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
        run:
            working-directory: "PocketPad Server"

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: "${{ github.workspace }}/PocketPad Server/server_app.py"
          mode: app
          product-name: PocketPad
          product-version: 1.0
          windows-icon-from-ico: "${{ github.workspace }}/PocketPad Server/icons/logo.png"
          macos-app-icon: "${{ github.workspace }}/PocketPad Server/icons/logo.png"
          macos-signed-app-name: "com.leemin.PocketPad-Server"
          macos-app-name: "PocketPad"
          macos-app-mode: gui
          macos-app-version: 1.0
          macos-app-protected-resource: "NSBluetoothAlwaysUsageDescription:We use Bluetooth to connect with your mobile device"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true