name: "Test Client and Server"

on:
    push:
    pull_request:

jobs:
    server:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - run: cd "PocketPad Server"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r "PocketPad Server/requirements.txt"
                  pip install -r "PocketPad Server/requirements-dev.txt"

            - run: sudo apt update && sudo apt install -y libegl1-mesa-dev
              if: matrix.os == 'ubuntu-latest'

            - name: Run client tests
              run: pytest "PocketPad Server/server_app_testing.py"