name: "Test Client and Server"

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    server:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, macos-latest]
                
        defaults:
            run:
                working-directory: "PocketPad Server"

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt

            - run: sudo apt update && sudo apt install -y libegl1-mesa-dev
              if: matrix.os == 'ubuntu-latest'

            - name: Run server tests
              run: pytest server_app_testing.py -vv -s
    client:
        runs-on: macos-latest

        defaults:
            run:
                working-directory: "PocketPad Client"

        steps:
            - uses: actions/checkout@v4

            - name: List available Xcode versions
              run: ls /Applications | grep Xcode
                
            - name: Set up Xcode version
              run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

            - run: xcodebuild -version

            - name: Run tests
              run: |
                xcodebuild test -scheme "PocketPad ClientTests" -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' CODE_SIGNING_ALLOWED='NO' | xcbeautify --renderer github-actions

            - name: Run UI tests
              run: |
                xcodebuild test -scheme "PocketPad ClientUITests" -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' CODE_SIGNING_ALLOWED='NO' | xcbeautify --renderer github-actions
